# Form implementation generated from reading ui file 'c:\Users\Dimitry\Python programs\lab-infa\UI\start_screen.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(843, 309)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.about_button = QtWidgets.QPushButton(Form)
        self.about_button.setObjectName("about_button")
        self.menu = QtWidgets.QButtonGroup(Form)
        self.menu.setObjectName("menu")
        self.menu.addButton(self.about_button)
        self.gridLayout.addWidget(self.about_button, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.game_button = QtWidgets.QPushButton(Form)
        self.game_button.setObjectName("game_button")
        self.gridLayout.addWidget(self.game_button, 3, 1, 1, 1)
        self.code_button = QtWidgets.QPushButton(Form)
        self.code_button.setObjectName("code_button")
        self.menu.addButton(self.code_button)
        self.gridLayout.addWidget(self.code_button, 1, 1, 1, 1)
        self.decode_button = QtWidgets.QPushButton(Form)
        self.decode_button.setObjectName("decode_button")
        self.menu.addButton(self.decode_button)
        self.gridLayout.addWidget(self.decode_button, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 7)
        self.gridLayout.setRowStretch(2, 7)
        self.gridLayout.setRowStretch(3, 7)
        self.gridLayout.setRowStretch(4, 7)
        self.gridLayout.setRowStretch(5, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.about_button.setText(_translate("Form", "О нас"))
        self.game_button.setText(_translate("Form", "Игра"))
        self.code_button.setText(_translate("Form", "Прямая задача"))
        self.decode_button.setText(_translate("Form", "Обратная задача"))
