# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\\decode_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(783, 570)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.run_button = QtWidgets.QPushButton(Form)
        self.run_button.setObjectName("run_button")
        self.gridLayout.addWidget(self.run_button, 6, 0, 1, 1)
        self.back_button = QtWidgets.QPushButton(Form)
        self.back_button.setObjectName("back_button")
        self.gridLayout.addWidget(self.back_button, 1, 0, 1, 1)
        self.output = QtWidgets.QLineEdit(Form)
        self.output.setText("")
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 7, 0, 1, 1)
        self.input = QtWidgets.QLineEdit(Form)
        self.input.setText("")
        self.input.setObjectName("input")
        self.gridLayout.addWidget(self.input, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.run_button.setText(_translate("Form", "Декодировать"))
        self.back_button.setText(_translate("Form", "Назад"))
